<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5b50bca4-b99e-43b1-a315-1ee13ac5f256</testSuiteGuid>
   <testCaseLink>
      <guid>28274e6b-cb08-45ea-9efb-3ab716ec09d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7dcad40e-19d7-45b4-9259-21822078e400</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7dcad40e-19d7-45b4-9259-21822078e400</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c0bdae08-a237-4f83-9ff3-486df5045476</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7dcad40e-19d7-45b4-9259-21822078e400</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>31dd6e53-8e65-4aed-a0cd-de755417ba26</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
